config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Home page
  root to: 'static_pages#home'

  # Static pages
  get 'static_pages/timer'
  get 'static_pages/dashboard'
  get 'static_pages/about'

  # Devise
  devise_for :users

  # --------- Routes declarations ---------
  resources :teas
  resources :infusions

  resources :users, only: %i[show edit]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/infusion.rb
# frozen_string_literal: true

class Infusion < ApplicationRecord
  # Validations
  validates :name, presence: true, length: { minimum: 2 }
  validates :infusion_time, presence: true
  validates :location, presence: true
  validates :brand, presence: true, length: { minimum: 1 }
  validates :description, presence: true, length: { in: 20..2000 }
  validates :grade, presence: true
  validates :user_id, presence: true

  # Relations
  belongs_to :user
end

app/models/tea.rb
# frozen_string_literal: true

class Tea < ApplicationRecord
  # Validations
  validates :name, presence: true, length: { minimum: 2 }
  validates :fermentation, presence: true
  validates :infusion_time, presence: true
  validates :location, presence: true
  validates :brand, presence: true, length: { minimum: 1 }
  validates :description, presence: true, length: { in: 20..2000 }
  validates :grade, presence: true
  validates :user_id, presence: true

  # Relations
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  #after_create :welcome_send

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Validations
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: true,
                    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: ' : Veuillez utiliser un email valide' }

  # Relations
  has_many :teas
  has_many :infusions

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation) }
  end
end

app/controllers/infusions_controller.rb
# frozen_string_literal: true

class InfusionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @infusions = Infusion.all
  end

  def show
    @infusion = Infusion.find(params[:id])
  end

  def new
    @infusion = Infusion.new
  end

  def create
    @infusion = Infusion.new(user_id: current_user.id, name: params[:name], infusion_time: params[:infusion_time], location: params[:location], brand: params[:brand], description: params[:description], grade: params[:grade])

    if @infusion.save
      redirect_to infusions_path(current_user.id)
      flash[:success] = "L'infusion a bien été ajoutée 👍"
    else
      render :new
    end
  end

  def edit
    @infusion = Infusion.find(params[:id])
  end

  def update
    @infusion = Infusion.find(params[:id])

    if @infusion.user == current_user
      if @infusion.update(user_id: current_user.id, name: params[:name], infusion_time: params[:infusion_time], location: params[:location], brand: params[:brand], description: params[:description], grade: params[:grade])
        redirect_to infusion_path(@infusion)
        flash[:success] = "L'infusion a bien été modifiée 👍"
      else
        flash[:alert] = "Vous n'avez pas rempli tous les champs, veuillez réessayer svp"
        render :edit
      end
    else
      redirect_to root_path, notice: "Vous ne pouvez pas éditer l'infusion d'autrui"
    end
  end

  def destroy
    @infusion = Infusion.find(params[:id])
    if @infusion.destroy
      redirect_to infusions_path
      flash[:success] = "L'infusion a bien été supprimée 👍"
    else
      flash[:alert] = 'Un problème est survenu'
      render :edit
    end
  end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end

  def timer; end

  def dashboard; end

  def about; end
end

app/controllers/teas_controller.rb
# frozen_string_literal: true

class TeasController < ApplicationController
  before_action :authenticate_user!

  def index
    @teas = Tea.all
  end

  def show
    @tea = Tea.find(params[:id])
  end

  def new
    @tea = Tea.new
  end

  def create
    @tea = Tea.new(user_id: current_user.id, name: params[:name], fermentation: params[:fermentation], infusion_time: params[:infusion_time], location: params[:location], brand: params[:brand], description: params[:description], grade: params[:grade])

    if @tea.save
      redirect_to teas_path(current_user.id)
      flash[:success] = 'Le thé a bien été ajouté 👍'
    else
      render :new
    end
  end

  def edit
    @tea = Tea.find(params[:id])
  end

  def update
    @tea = Tea.find(params[:id])

    if @tea.user == current_user
      if @tea.update(user_id: current_user.id, name: params[:name], fermentation: params[:fermentation], infusion_time: params[:infusion_time], location: params[:location], brand: params[:brand], description: params[:description], grade: params[:grade])
        redirect_to tea_path(@tea)
        flash[:success] = 'Le thé a bien été modifié 👍'
      else
        flash[:alert] = "Vous n'avez pas rempli tous les champs, veuillez réessayer svp"
        render :edit
      end
    else
      redirect_to root_path, notice: "Vous ne pouvez pas éditer le thé d'autrui"
    end
  end

  def destroy
    @tea = Tea.find(params[:id])
    if @tea.destroy
      redirect_to teas_path
      flash[:success] = 'Le thé a bien été supprimé 👍'
    else
      flash[:alert] = 'Un problème est survenu'
      render :edit
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :dont_show
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
  end

  def dont_show
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to root_path flash[:alert] = 'Information confidentielle'
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  # Flash messages
  def flash_class(level)
    case level
    when 'notice' then 'alert alert-info alert-dismissible fade show '
    when 'success' then 'alert alert-success alert-dismissible fade show'
    when 'error' then 'alert alert-danger alert-dismissible fade show'
    when 'alert' then 'alert alert-warning alert-dismissible fade show'
    end
  end
end

app/helpers/infusions_helper.rb
# frozen_string_literal: true

module InfusionsHelper
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

module StaticPagesHelper
end

app/helpers/teas_helper.rb
# frozen_string_literal: true

module TeasHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/infusions/_error_messages.html.erb
<% if @infusion.errors.any? %>
  <div id="error_explanation" data-dismiss="alert" class="alert alert-danger" role="alert" aria-label="Close">
    <ul>
      <% @infusion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/infusions/index.html.erb
<%= render 'layouts/dashboard' %>
<div id="content">
	<!-- Begin Page Content -->
	<div class="container-fluid">

		<!-- Page Heading -->
		<div class="d-sm-flex align-items-center justify-content-between mb-4">
			<h2 class="h3 mb-0 text-gray-800">Ma théière</h2>
		</div>
		<p class="mt-3">
			<% if current_user.infusions.count == 0 %>
			<h4><i class="fas fa-box-open mr-1"></i>Vous n'avez pas encore d'infusions dans votre boîte à infusions <i class="fas fa-leaf text-success"></i></h4><%= link_to(new_infusion_path, class: "btn btn-success btn-icon-split") do %>
			<span class="icon text-white-40">
				<i class="fas fa-plus-square"></i>
			</span>
			<span class="text">Ajouter une infusion</span>
			<% end %>
			<% elsif current_user.infusions.count == 1 || current_user.infusions.count == 0 %>
			<h4><i class="fas fa-box-open mr-1"></i>Ma boîte à infusions : <%= current_user.infusions.count %> infusion 🌿</h4>
			<% else %>
			<h4><i class="fas fa-box-open mr-1"></i>Ma boîte à infusions : <%= current_user.infusions.count %> infusions 🌿</h4>
			<% end %>
		</p>
		<div class="row">
			<% current_user.infusions.each do |i| %>
			<div class="col col-md-4 mb-4">
				<div class="card card-me h-100 py-2 shadow">
					<%= link_to(infusion_path(i.id)) do %>
					<div class="card-body">
						<div class="row no-gutters align-items-center">
							<div class="col mr-2">
								<div class="font-weight-bold text-success text-uppercase mb-1"><%= i.name %></div>
								<div class="h5 mb-0 mt-2 text-xs text-gray-800"><i class="fas fa-clock mr-1"></i><%= i.infusion_time %> minutes d'infusion</div>
							</div>
							<div class="col-auto">
								<i class="fas fa-leaf fa-2x text-success"></i>
							</div>
						</div>
					</div>
					<% end %>
				</div>
			</div>
			<% end %>
		</div>
	</div>
	<!-- End of Main Content -->
</div>

app/views/infusions/show.html.erb
<!-- Dashboard partial -->
<%= render 'layouts/dashboard' %>

<!-- Show tea -->
<div id="content">
  <!-- Begin Page Content -->
  <div class="container-fluid">
    <div class="card shadow border-bottom-success col col-8 mx-auto">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-success"><%= @infusion.name %></h6>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col col-3">
           <% if @infusion.infusion_time > 1 %>
           <p><i class="fas fa-stopwatch mr-1 text-success"></i><%= @infusion.infusion_time %> minutes</p>
           <% else %>
           <p><i class="fas fa-stopwatch mr-1 text-success"></i><%= @infusion.infusion_time %> minute</p>
           <% end %>
           <p><i class="fas fa-globe-americas mr-1 text-success"></i><%= @infusion.location %></p>
         </div>
         <div class="col col-4">
          <p><i class="far fa-registered mr-1 text-success"></i><%= @infusion.brand %></p>
          <p><% if @infusion.grade == 0 %>
          Note : <i class="fas fa-leaf"></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i>
          <% elsif @infusion.grade == 1 %>
          Note : <i class="fas fa-leaf text-success"></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i>
          <% elsif @infusion.grade == 2 %>
          Note : <i class="fas fa-leaf text-success"></i><i class="fas fa-leaf text-success"></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i>
          <% elsif @infusion.grade == 3 %>
          Note : <i class="fas fa-leaf text-success"></i><i class="fas fa-leaf text-success"></i><i class="fas fa-leaf text-success"></i><i class="fas fa-leaf"></i><i class="fas fa-leaf"></i>
          <% elsif @infusion.grade == 4 %>
          Note : <i class="fas fa-leaf text-success"></i><i class="fas fa-leaf text-success"></i><i class="fas fa-leaf text-success"></i><i class="fas fa-leaf text-success"></i><i class="fas fa-leaf"></i>
          <% elsif @infusion.grade == 5%>
          Note : <i class="fas fa-leaf text-success"></i><i class="fas fa-leaf text-success"></i><i class="fas fa-leaf text-success"></i><i class="fas fa-leaf text-success"></i><i class="fas fa-leaf text-success"></i>
          <% end %></p>
        </div>
      </div>
      <hr>
      
      <div class="row mb-2">
        <b class="mr-1">Description : </b>
        <p><%= @infusion.description %></p>
      </div>
      <hr>
      <div class="row">
        <div class="col">
          <%= link_to((edit_infusion_path), class: "btn btn-success btn-icon-split mr-2") do %>
          <span class="icon text-white-50">
            <i class="fas fa-pen"></i>
          </span>
          <span class="text">Éditer</span>
          <% end %>
          <%= link_to(infusion_path(@infusion), method: :delete, class: "btn btn-danger btn-icon-split", data: { confirm: 'Êtes-vous sûr(e) ?'}) do %>
          <span class="icon text-white-50">
            <i class="fas fa-trash"></i>
          </span>
          <span class="text">Supprimer</span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/layouts/_dashboard.html.erb
<!-- Page Wrapper -->
<div id="wrapper">

  <!-- Sidebar -->
  <ul class="navbar-nav bg-gradient-success  sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <%= link_to(root_path, class: "sidebar-brand d-flex align-items-center justify-content-center") do %>
      <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-mug-hot"></i>
      </div>
      <div class="sidebar-brand-text mx-3">ADDICT TEA</div>
    <% end %>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
      <%= link_to(static_pages_dashboard_path(current_user.id), class: "nav-link") do %>
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span>
      <% end %>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
      Ma théière
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
      <%= link_to(teas_path(current_user.id), class: "nav-link") do %>
      <i class="fas fa-mug-hot"></i>
      <span>Mes thés</span>
      <% end %>
      <%= link_to(infusions_path(current_user.id), class: "nav-link") do %>
      <i class="fas fa-mug-hot"></i>
      <span>Mes infusions</span>
      <% end %>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
     <%= link_to(static_pages_timer_path, class: "nav-link") do %>
     <i class="fas fa-stopwatch"></i>
     Timer
     <% end %>
   </li>

   <!-- Divider -->
   <hr class="sidebar-divider">

   <!-- Heading -->
   <div class="sidebar-heading">
    Autres
  </div>

  <!-- Nav Item - Charts -->
  <li class="nav-item">

    <!-- Nav Item - Tables -->
    <li class="nav-item">
      <%= link_to(root_path, class: "nav-link") do %>
        <i class="fas fa-home"></i>
        <span>Page d'accueil</span>
      <% end %>
      <%= link_to(static_pages_about_path, class: "nav-link") do %>
        <i class="fas fa-address-card"></i>
        <span>À propos</span>
      <% end %>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>
    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
          

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>
          <%= link_to(new_tea_path, class: "btn btn-success btn-icon-split") do %>
          <span class="icon text-white-40">
            <i class="fas fa-plus-square"></i>
          </span>
          <span class="text">Ajouter un thé</span>
          <% end %>

          <%= link_to(new_infusion_path, class: "btn btn-success btn-icon-split ml-3") do %>
          <span class="icon text-white-40">
            <i class="fas fa-plus-square"></i>
          </span>
          <span class="text">Ajouter une infusion</span>
          <% end %>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.first_name %> <%= current_user.last_name %></span>
                <img class="img-profile rounded-circle" src="https://cdn.pixabay.com/photo/2016/08/20/05/38/avatar-1606916_1280.png">
              </a>
            </li>
          </ul>
        </nav>
        <!-- End of Topbar -->

app/views/layouts/_flash.html.erb
<!-- Partial for the flash alerts -->
<% flash.each do |key, value| %>
	<div class="<%= flash_class(key) %> delay_fadeout flash-screen" style="position:absolute; top: 80px; width:100%; z-index:3">
		<%= value %>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">&times;</span></button>
	</div>
<% end %>

app/views/static_pages/dashboard.html.erb
<%= render 'layouts/dashboard' %>
<div id="content">
	<!-- Begin Page Content -->
	<div class="container-fluid">

		<!-- Page Heading -->
		<div class="d-sm-flex align-items-center justify-content-between mb-4">
			<h2 class="h3 mb-3 text-gray-800">Mon dashboard</h2>
		</div>

		<div class="row">
			<div class="col border-right border-success">

			<p class="mt-3">
				<% if current_user.teas.count == 0 %>
				<h4><i class="fas fa-box-open mr-1"></i>Vous n'avez pas encore de thés dans votre boîte à thés <i class="fas fa-leaf text-success"></i></h4>
				<% elsif current_user.teas.count == 1 || current_user.teas.count == 0 %>
				<h4><i class="fas fa-box-open mr-1"></i>Ma boîte à thés : <%= current_user.teas.count %> thé 🌿</h4>
				<% else %>
				<h4><i class="fas fa-box-open mr-1"></i>Ma boîte à thés : <%= current_user.teas.count %> thés 🌿</h4>
				<% end %>
				<%= link_to(new_tea_path, class: "btn btn-success btn-icon-split") do %>
				<span class="icon text-white-40">
					<i class="fas fa-plus-square"></i>
				</span>
				<span class="text">Ajouter un thé</span>
				<% end %>
			</p>

			<p class="mt-4">
				<% if current_user.infusions.count == 0 %>
				<h4><i class="fas fa-box-open mr-1"></i>Vous n'avez pas encore d'infusions dans votre boîte à infusions <i class="fas fa-leaf text-success"></i></h4>
				<% elsif current_user.infusions.count == 1 || current_user.infusions.count == 0 %>
				<h4><i class="fas fa-box-open mr-1"></i>Ma boîte à infusions : <%= current_user.infusions.count %> infusion 🌿</h4>
				<% else %>
				<h4><i class="fas fa-box-open mr-1"></i>Ma boîte à infusions : <%= current_user.infusions.count %> infusions 🌿</h4>
				<% end %>
				<%= link_to(new_infusion_path, class: "btn btn-success btn-icon-split") do %>
				<span class="icon text-white-40">
					<i class="fas fa-plus-square"></i>
				</span>
				<span class="text">Ajouter une infusion</span>
				<% end %>
			</p>
			</div>
			
			<div class="col mt-3 ml-3">
				<h4>Mon profil</h4>
				<hr>
				<p><%= current_user.first_name %> <%= current_user.last_name %><br>
					<%= current_user.email %>
				</p>
				
			<p>
				<%= link_to(edit_user_registration_path, class: "btn btn-info btn-icon-split") do %>
				<span class="icon text-white-40">
					<i class="fas fa-user-cog"></i>
				</span>
				<span class="text">Éditer mon profil</span>
				<% end %> 
			</p>
			</div>
		</div>
		
	</div>
</div>

app/views/static_pages/home.html.erb
<section style="opacity: 0.9;">
  <header class="masthead d-flex">
    <div class="container text-center my-auto">
      <h1 class="mb-1">ADDICT TEA</h1>
      <h3 class="mb-5">
        <em>Vos tea times vont changer !</em> 🌿
      </h3>

      <% if user_signed_in? %>
      <%= link_to "Mon dashboard", static_pages_dashboard_path(current_user.id), class: "btn btn-success shadow mr-2" %>
        <%= link_to "Se déconnecter", destroy_user_session_path, method: 'delete', class: " btn btn-danger shadow" %>
      <% else %>
        <%= link_to "Connexion", new_user_session_path, class: "btn btn-success shadow mr-2" %>
        <%= link_to "Inscription", new_user_registration_path, class: "btn btn-success shadow" %>
      <% end %>
    </div>
    <div class="overlay"></div>
  </header>
</section>  

app/views/teas/_dashboard.html.erb
<!-- Page Wrapper -->
<div id="wrapper">

  <!-- Sidebar -->
  <ul class="navbar-nav bg-gradient-success  sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <%= link_to(teas_path(current_user.id), class: "sidebar-brand d-flex align-items-center justify-content-center") do %>
      <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-mug-hot"></i>
      </div>
      <div class="sidebar-brand-text mx-3">ADDICT TEA</div>
    <% end %>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
      <%= link_to(teas_path(current_user.id), class: "nav-link") do %>
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span>
      <% end %>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
      Ma théière
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
      <%= link_to(teas_path(current_user.id), class: "nav-link") do %>
      <i class="fas fa-mug-hot"></i>
      <span>Mes thés</span>
      <% end %>
      <%= link_to(teas_path(current_user.id), class: "nav-link") do %>
      <i class="fas fa-mug-hot"></i>
      <span>Mes infusions</span>
      <% end %>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
     <%= link_to(static_pages_timer_path, class: "nav-link") do %>
     <i class="fas fa-stopwatch"></i>
     Timer
     <% end %>
   </li>

   <!-- Divider -->
   <hr class="sidebar-divider">

   <!-- Heading -->
   <div class="sidebar-heading">
    Autres
  </div>

  <!-- Nav Item - Charts -->
  <li class="nav-item">

    <!-- Nav Item - Tables -->
    <li class="nav-item">
      <a class="nav-link" href="tables.html">
        <i class="fas fa-address-card"></i>
        <span>À propos</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>
    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
          <form class="d-none d-sm-inline-block form-inline mr-3 ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Recherche.." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-success" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>
          <%= link_to(new_tea_path, class: "btn btn-success btn-icon-split") do %>
          <span class="icon text-white-40">
            <i class="fas fa-plus-square"></i>
          </span>
          <span class="text">Ajouter un thé</span>
          <% end %>

          <%= link_to(edit_user_registration_path, class: "btn btn-info btn-icon-split ml-3") do %>
          <span class="icon text-white-40">
            <i class="fas fa-user-cog"></i>
          </span>
          <span class="text">Éditer mon profil</span>
          <% end %> 

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.first_name %> <%= current_user.last_name %></span>
                <img class="img-profile rounded-circle" src="https://cdn.pixabay.com/photo/2016/08/20/05/38/avatar-1606916_1280.png">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Mon profil
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Éditer mon profil
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Déconnexion
                </a>
              </div>
            </li>
          </ul>
        </nav>
        <!-- End of Topbar -->

app/views/teas/_error_messages.html.erb
<% if @tea.errors.any? %>
  <div id="error_explanation" data-dismiss="alert" class="alert alert-danger" role="alert" aria-label="Close">
    <ul>
      <% @tea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>